name: Deploy Opensource Image to GHCR

on:
  push:
    branches: [ "ros1_noetic" ]
  pull_request:
    branches: [ "ros1_noetic" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v3

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: "Build the Docker image"
      run: |
        mkdir src
        echo "jupyterlab" > requirements.txt
        docker build . --file .github/workflows/Dockerfile.ros1_noetic --tag ghcr.io/simonschwaiger/ros-ml-container:ros1_noetic
        docker push ghcr.io/simonschwaiger/ros-ml-container:ros1_noetic